development:
  adapter: mysql2
  host: 
  database: 
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  host: localhost
  database: vp_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: 
  database:
  pool: 5
  timeout: 5000